// src/lib/products.js
export const products = [
  {
    id: 1,
    name: 'Sunbeam Tote Jeff',
    price: 25.00,
    imageSrc: '/img/coffee_table.jpg',
    imageAlt: 'Brown tote bag with floral embossing',
    featured: true,
    onSale: false,
  },
  {
    id: 2,
    name: 'ShadowStride Shoes',
    price: 20.00,
    salePrice: 15.00,
    imageSrc: '/img/glass_table.jpg',
    imageAlt: 'Navy canvas sneakers',
    featured: false,
    onSale: true,
  },
  {
    id: 3,
    name: 'Horizon Gaze Sunglasses',
    price: 20.00,
    imageSrc: '/img/wooden_table.jpg',
    imageAlt: 'Black frame sunglasses with brown lenses',
    featured: true,
    onSale: false,
  },
  {
    id: 4,
    name: 'Sunbeam Tote Jeff',
    price: 25.00,
    imageSrc: '/img/yelllow_chair.jpg',
    imageAlt: 'Brown tote bag with floral embossing',
    featured: true,
    onSale: false,
  },
  {
    id: 5,
    name: 'ShadowStride Shoes',
    price: 20.00,
    salePrice: 18.00,
    imageSrc: '/img/green_couch.jpg',
    imageAlt: 'Navy canvas sneakers',
    featured: false,
    onSale: true,
  },
  {
    id: 6,
    name: 'Horizon Gaze Sunglasses',
    price: 20.00,
    imageSrc: '/img/test.jpg',
    imageAlt: 'Black frame sunglasses with brown lenses',
    featured: false,
    onSale: false,
  },
  {
    id: 7,
    name: 'Sunbeam Tote Jeff',
    price: 25.00,
    imageSrc: '/img/watch.jpg',
    imageAlt: 'Brown tote bag with floral embossing',
    featured: true,
    onSale: false,
  },
  {
    id: 8,
    name: 'ShadowStride Shoes',
    price: 20.00,
    salePrice: 16.00,
    imageSrc: '/img/smart_watch.jpg',
    imageAlt: 'Navy canvas sneakers',
    featured: false,
    onSale: true,
  },
  {
    id: 9,
    name: 'ShadowStride Shoes',
    price: 20.00,
    imageSrc: '/img/bag.jpg',
    imageAlt: 'Navy canvas sneakers',
    featured: false,
    onSale: false,
  },
];
